# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# See the documentation for all configuration options:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` in the `root` directory
    directory: "/"
    # Check for npm updates daily
    schedule:
      interval: "daily"
    # Create pull requests for security updates immediately
    open-pull-requests-limit: 10
    # Apply labels to pull requests
    labels:
      - "dependencies"
      - "javascript"
    # Group updates by dependency name
    versioning-strategy: "increase"
    # Only allow updates to the patch and minor version for 0.x and 1.x
    ignore:
      # Ignore updates for packages with breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Automatically merge minor and patch updates
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    # Rebase strategy
    rebase-strategy: "auto"
    # Target branch for pull requests
    target-branch: "develop"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # Configuration for backend API
  - package-ecosystem: "npm"
    directory: "/tools-restructured/services/backend-api"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend-deps)"
      include: "scope"
    # Group updates by dependency name
    versioning-strategy: "increase"
    # Only allow updates to the patch and minor version for 0.x and 1.x
    ignore:
      # Ignore updates for packages with breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

# Configuration for security updates
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Apply security updates immediately
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
    # Allow all update types for security updates
    allow:
      - dependency-type: "all"
    # Auto-merge security patches
    commit-message:
      prefix: "security"
      include: "scope"
    # Rebase strategy
    rebase-strategy: "auto"
    # Target branch for security updates
    target-branch: "main"
    # Apply security updates to all dependencies
    versioning-strategy: "auto"
