# Dependabot configuration file
# Learn more: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # === Root NPM (Frontend / Core App) ===
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "javascript"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"

  # === Backend API (Node.js) ===
  - package-ecosystem: "npm"
    directory: "/services/backend-api"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "backend"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(backend-deps)"
      include: "scope"

  # === Frontend (React / Web UI) ===
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "frontend"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(frontend-deps)"
      include: "scope"

  # === Shared NPM Packages ===
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "shared"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(shared-deps)"
      include: "scope"

  # === Python Services ===
  - package-ecosystem: "pip"
    directory: "/services/ai-behavioral-nudge-engine"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(python-deps)"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/portfolio-simulation"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(python-deps)"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/python-risk-engine"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(python-deps)"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/market-data-ingestion"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(python-deps)"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/ai-microservice-engine"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(python-deps)"
      include: "scope"

  # === Docker ===
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # === GitHub Actions ===
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"

  # === Security Updates (All Dependencies) ===
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "security"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "auto"
