version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  python-engine:
    build: ./python-engine
    env_file:
      - ./python-engine/.env
    volumes:
      - ./python-engine:/app
    depends_on:
      - backend
