envGroups:
  - name: shared-secrets
    envVars:
      - key: REDIS_URL
        sync: false
      - key: MARKET_DATA_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BEHAVIORAL_NUDGE_API_KEY
        sync: false

services:
  # Backend API 
  - type: web
    name: backend-api
    runtime: image
    image:
      url: karingler/backend-api:latest
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: SERVICE_AUTH_SECRET
        generateValue: true
      - key: DATABASE_ENCRYPTION_KEY
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend.vercel.app
    autoDeploy: true

  # Market Data Ingestion Service
  - type: web
    name: marketdata-ingestion
    runtime: image
    image:
      url: karingler/marketdata-ingestion:latest
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: PORT
        value: 3002
    autoDeploy: true

  # AI Microservice Engine
  - type: web
    name: ai-microservice-engine
    runtime: image
    image:
      url: karingler/ai-microservice-engine:latest
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: PORT
        value: 3003
      - key: AI_MODEL_VERSION
        value: gpt-4
      - key: AI_TEMPERATURE
        value: "0.7"
      - key: AI_MAX_TOKENS
        value: "150"
      - key: BEHAVIORAL_NUDGE_ENABLED
        value: "true"
    autoDeploy: true

  # Python Risk Engine
  - type: web
    name: python-risk-engine
    runtime: image
    image:
      url: karingler/python-risk-engine:latest
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: PORT
        value: 3001
      - key: RISK_CALCULATION_WORKERS
        value: "2"
    autoDeploy: true

  # Portfolio Simulation Service
  - type: web
    name: portfolio-simulation
    runtime: image
    image:
      url: karingler/portfolio-simulation:latest
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: PORT
        value: 3004
      - key: RISK_ENGINE_URL
        value: https://python-risk-engine.onrender.com
      - key: MARKET_DATA_URL
        value: https://marketdata-ingestion.onrender.com
      - key: AI_SERVICE_URL
        value: https://ai-microservice-engine.onrender.com
    autoDeploy: true

  # Behavioral Nudge Engine Service
  - type: web
    name: behavioral-nudge-engine
    runtime: image
    image:
      url: karingler/behavioral-nudge-engine:latest
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: PORT
        value: 8000
    autoDeploy: true

databases:
- name: beginner-investor-db
  databaseName: investment_hub
  user: investment_hub_user
  plan: free
  region: virginia
  ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere
  postgresMajorVersion: "17"

# Environment Groups Configuration (CRITICAL)
# IMPORTANT: Create an environment group named 'shared-secrets' in your Render dashboard
# and add these environment variables to it:
#
# 1. REDIS_URL: Your external Redis Cloud connection string
#    Example: redis://username:password@host:port
#
# 2. API Keys:
#    - MARKET_DATA_API_KEY (for marketdata-ingestion)
#    - FINNHUB_API_KEY (for marketdata-ingestion)
#    - ALPHA_VANTAGE_API_KEY (for marketdata-ingestion)
#    - OPENAI_API_KEY (for ai-microservice-engine)
#    - BEHAVIORAL_NUDGE_API_KEY (for behavioral-nudge-engine)
#
# These are shared across services via the 'shared-secrets' environment group.
