# render.yaml - Render Blueprint for Beginner Investor Hub
# Firebase: Authentication | Learning Hub: AI-Powered Gamification
services:
  # Core Backend API - Entry point with Firebase auth
  - type: web
    name: backend-api-service
    env: node
    buildCommand: |
      npm install
      cd tools-restructured/services/backend-api && npm install
    startCommand: node tools-restructured/services/backend-api/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Firebase Authentication
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_WEB_API_KEY
        sync: false
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      # Internal service URLs
      - key: AI_MICROSERVICE_URL
        value: https://ai-microservice-engine.onrender.com
      - key: PORTFOLIO_SIMULATION_URL
        value: https://portfolio-simulation-service.onrender.com
      - key: MARKET_DATA_URL
        value: https://market-data-ingestion-service.onrender.com
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health
    
  # AI Microservice Engine - Powers AI behavioral nudge + Learning Hub
  - type: web
    name: ai-microservice-engine
    env: node
    buildCommand: |
      npm install
      cd tools-restructured/services/ai_microservice && npm install
    startCommand: node tools-restructured/services/ai_microservice/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
      # OpenAI Configuration
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_API_ENDPOINT
        value: https://api.openai.com/v1
      - key: OPENAI_MODEL
        value: gpt-4
      # Firebase for token verification
      - key: FIREBASE_PROJECT_ID
        sync: false
      # Learning Hub & Gamification
      - key: BEHAVIORAL_NUDGE_ENABLED
        value: true
      - key: LEARNING_HUB_ENABLED
        value: true
      - key: GAMIFICATION_ENABLED
        value: true
      # Database for user progress tracking
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
    healthCheckPath: /health

  # Python Risk Engine
  - type: web
    name: python-risk-engine
    env: python
    buildCommand: |
      cd tools-restructured/services/python-engine
      pip install -r requirements.txt
    startCommand: python tools-restructured/services/python-engine/app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10002
      # Firebase for token verification
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: RISK_CALCULATION_ENABLED
        value: true
    healthCheckPath: /health

  # Market Data Ingestion
  - type: web
    name: market-data-ingestion-service
    env: node
    buildCommand: |
      npm install
      cd tools-restructured/services/market-data-ingestion && npm install
    startCommand: node tools-restructured/services/market-data-ingestion/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10003
      # Database for persistent storage
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      # Market Data APIs
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: MARKET_DATA_API_KEY
        sync: false
      # Firebase for admin operations
      - key: FIREBASE_PROJECT_ID
        sync: false
    healthCheckPath: /health

  # Portfolio Simulation
  - type: web
    name: portfolio-simulation-service
    env: node
    buildCommand: |
      npm install
      cd tools-restructured/services/portfolio-simulation && npm install
    startCommand: node tools-restructured/services/portfolio-simulation/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10004
      # Database for user portfolios
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      # Dependent services
      - key: PYTHON_RISK_ENGINE_URL
        value: https://python-risk-engine.onrender.com
      - key: MARKET_DATA_URL
        value: https://market-data-ingestion-service.onrender.com
      # Firebase for user authentication
      - key: FIREBASE_PROJECT_ID
        sync: false
    healthCheckPath: /health
databases:
  # PostgreSQL Database for persistent data
  - name: beginner-investor-db
    databaseName: beginner_investor_hub
    user: postgres
