services:
  # Backend API
  - type: web
    name: backend-api
    runtime: docker
    dockerfilePath: services/backend-api/Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: beginner-investor
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: beginner-investor-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: SERVICE_AUTH_SECRET
        generateValue: true
      - key: DATABASE_ENCRYPTION_KEY
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend.vercel.app,https://backend-api-n7cq.onrender.com,https://market-data-ingestion-service-l5n1.onrender.com,https://ai-microservice-engine.onrender.com,https://python-risk-engine.onrender.com,https://portfolio-simulation.onrender.com,https://behavioral-nudge-engine.onrender.com
      - key: MARKET_DATA_URL
        value: https://market-data-ingestion-service-l5n1.onrender.com
      - key: AI_SERVICE_URL
        value: https://ai-microservice-engine.onrender.com
      - key: RISK_ENGINE_URL
        value: https://python-risk-engine.onrender.com
      - key: PORTFOLIO_SIMULATION_URL
        value: https://portfolio-simulation.onrender.com
      - key: BEHAVIORAL_NUDGE_URL
        value: https://behavioral-nudge-engine.onrender.com
    autoDeploy: true

  # MarketData-Ingestion
  - type: web
    name: marketdata-ingestion
    runtime: docker
    dockerfilePath: services/marketdata-ingestion/Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: beginner-investor
      - key: DATABASE_URL
        value: postgresql://investment_hub_user:HthtLQ7nwPVwwKuyHAL6gfMOUVtGgG5m@dpg-d2v0j4buibrs7384kr80-a/investment_hub_9nuh
      - key: PORT
        value: 3002
      - key: BACKEND_API_URL
        value: https://backend-api-n7cq.onrender.com
    autoDeploy: true

  # AI Microservice Engine
  - type: web
    name: ai-microservice-engine
    runtime: docker
    dockerfilePath: services/ai-microservice-engine/Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: beginner-investor
      - key: DATABASE_URL
        value: postgresql://investment_hub_user:HthtLQ7nwPVwwKuyHAL6gfMOUVtGgG5m@dpg-d2v0j4buibrs7384kr80-a/investment_hub_9nuh
      - key: PORT
        value: 3003
      - key: AI_MODEL_VERSION
        value: gpt-4
      - key: AI_TEMPERATURE
        value: "0.7"
      - key: AI_MAX_TOKENS
        value: "150"
      - key: BEHAVIORAL_NUDGE_ENABLED
        value: "true"
      - key: BACKEND_API_URL
        value: https://backend-api-n7cq.onrender.com
      - key: MARKET_DATA_URL
        value: https://market-data-ingestion-service-l5n1.onrender.com
    autoDeploy: true

  # Python Risk Engine
  - type: web
    name: python-risk-engine
    runtime: docker
    dockerfilePath: services/python-risk-engine/Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: beginner-investor
      - key: DATABASE_URL
        value: postgresql://investment_hub_user:HthtLQ7nwPVwwKuyHAL6gfMOUVtGgG5m@dpg-d2v0j4buibrs7384kr80-a/investment_hub_9nuh
      - key: PORT
        value: 3001
      - key: RISK_CALCULATION_WORKERS
        value: "2"
      - key: BACKEND_API_URL
        value: https://backend-api-n7cq.onrender.com
      - key: MARKET_DATA_URL
        value: https://market-data-ingestion-service-l5n1.onrender.com
    autoDeploy: true

  # Portfolio Simulation Service
  - type: web
    name: portfolio-simulation
    runtime: docker
    dockerfilePath: services/portfolio-simulation/Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: beginner-investor
      - key: DATABASE_URL
        value: postgresql://investment_hub_user:HthtLQ7nwPVwwKuyHAL6gfMOUVtGgG5m@dpg-d2v0j4buibrs7384kr80-a/investment_hub_9nuh
      - key: PORT
        value: 3004
      - key: RISK_ENGINE_URL
        value: https://python-risk-engine.onrender.com
      - key: MARKET_DATA_URL
        value: https://market-data-ingestion-service-l5n1.onrender.com
      - key: AI_SERVICE_URL
        value: https://ai-microservice-engine.onrender.com
      - key: BACKEND_API_URL
        value: https://backend-api-n7cq.onrender.com
    autoDeploy: true

  # Behavioral Nudge Engine Service
  - type: web
    name: behavioral-nudge-engine
    runtime: docker
    dockerfilePath: services/behavioral-nudge-engine/Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - fromGroup: beginner-investor
      - key: DATABASE_URL
        value: postgresql://investment_hub_user:HthtLQ7nwPVwwKuyHAL6gfMOUVtGgG5m@dpg-d2v0j4buibrs7384kr80-a/investment_hub_9nuh
      - key: PORT
        value: 8000
      - key: BACKEND_API_URL
        value: https://backend-api-n7cq.onrender.com
    autoDeploy: true

databases:
  - name: beginner-investor-db
    databaseName: investment_hub
    user: investment_hub_user
    plan: free
    region: virginia
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "17"
