groups:
- name: instance-down
  rules:
    - alert: InstanceDown
      expr: up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

- name: high-request-latency
  rules:
    - alert: APIHighRequestLatency
      expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High request latency on {{ $labels.instance }}"
        description: "API instance {{ $labels.instance }} has 99th percentile request latency above 1s (current value: {{ $value }}s)"

- name: error-rate
  rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.01
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate on {{ $labels.instance }}"
        description: "High error rate on {{ $labels.instance }}: {{ $value }}% of requests are failing"

- name: resource-usage
  rules:
    - alert: HighMemoryUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage on {{ $labels.instance }}"
        description: "Memory usage is {{ $value }}%"

    - alert: HighCPUUsage
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on {{ $labels.instance }}"
        description: "CPU usage is {{ $value }}%"

- name: database
  rules:
    - alert: HighPostgresConnections
      expr: pg_stat_activity_count > 50
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High number of PostgreSQL connections on {{ $labels.instance }}"
        description: "Number of connections: {{ $value }}"

    - alert: RedisDown
      expr: redis_up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Redis instance {{ $labels.instance }} is down"

- name: application-specific
  rules:
    - alert: HighRequestRate
      expr: rate(http_requests_total[5m]) > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High request rate on {{ $labels.instance }}"
        description: "Request rate: {{ $value }} req/s"

    - alert: JobQueueBacklog
      expr: job_queue_size > 100
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Job queue backlog on {{ $labels.instance }}"
        description: "Job queue size: {{ $value }}"
