global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Alert rules
rule_files:
  - 'alert.rules.yml'

# Scrape configurations
scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Backend API
  - job_name: 'backend-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-api:3000']
    
  # Frontend
  - job_name: 'frontend'
    metrics_path: '/_next/static/__next-static/__statsig__/metrics'
    static_configs:
      - targets: ['frontend:3000']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  # Postgres
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Blackbox exporter for HTTP/HTTPS checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'http://frontend:3000'    # Frontend health check
        - 'http://backend-api:3000/health'  # Backend health check
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
