global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: '${ALERT_EMAIL_USER}'
  smtp_auth_password: '${ALERT_EMAIL_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'
  routes:
    - match:
        severity: 'critical'
      receiver: 'email-and-slack'
    - match:
        alertname: 'Watchdog'
      receiver: 'null'

receivers:
  - name: 'email'
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
        send_resolved: true
        headers:
          subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'
  
  - name: 'email-and-slack'
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
        send_resolved: true
    webhook_configs:
      - url: '${SLACK_WEBHOOK_URL}'
        send_resolved: true
  
  - name: 'null'

# Templates for email notifications
templates:
  - '/etc/alertmanager/template/*.tmpl'
