name: Build and Deploy to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'
      - '.github/workflows/render-deploy.yml'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          curl -o render https://render.com/download/cli/latest/linux-amd64
          chmod +x render
          sudo mv render /usr/local/bin/

      - name: Login to Render
        run: |
          echo "${{ secrets.RENDER_API_KEY }}" | render login

      - name: Deploy to Render
        run: |
          render blueprint launch
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'backend-api-service',
          'market-data-ingestion-service',
          'ai-microservice-engine',
          'python-risk-engine',
          'portfolio-simulation-service'
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            karingler/${{ matrix.service }}:latest
            karingler/${{ matrix.service }}:${{ github.sha }}